In [1]:
import pandas as pd
import numpy as np

/usr/local/lib/python3.9/dist-packages/pandas/compat/_optional.py:161: UserWarning: Pandas requires version '1.3.1' or newer of 'bottleneck' (version '1.2.1' currently installed).
  warnings.warn(msg, UserWarning)

In [17]:
prstcan = "/homes/mcenfeng/Documents/MAGMA/gene_output_prstcan.genes.out"
prstcan

'/homes/mcenfeng/Documents/MAGMA/gene_output_prstcan.genes.out'

In [18]:
data_prstcan = pd.read_fwf(prstcan, sep="\t")
data_prstcan.head(10)

,GENE,CHR,START,STOP,NSNPS,NPARAM,N,ZSTAT,P
0,ENSG00000237683,1,134901,139379,2,1,140306,0.386570,0.34954
1,ENSG00000269831,1,738532,739137,2,1,140306,0.695570,0.24335
2,ENSG00000269308,1,818043,819983,2,1,140306,-2.588600,0.99518
3,ENSG00000187634,1,860260,879955,91,23,140306,-0.218360,0.58643
4,ENSG00000268179,1,861264,866445,34,10,140306,-0.285670,0.61243
5,ENSG00000188976,1,879584,894689,72,14,140306,-0.980120,0.83649
6,ENSG00000187961,1,895967,901095,37,8,140306,-2.655300,0.99604
7,ENSG00000187583,1,901877,911245,50,21,140306,-0.440760,0.67031
8,ENSG00000187642,1,910579,917497,26,7,140306,-0.013732,0.50548
9,ENSG00000188290,1,934342,935552,5,2,140306,-0.535570,0.70387

In [19]:
data_prstcan.drop(['CHR', 'START', 'STOP', 'NSNPS', 'NPARAM', 'N', 'ZSTAT'], inplace=True, axis=1)

In [20]:
data_prstcan

                  GENE         P
0      ENSG00000237683  0.349540
1      ENSG00000269831  0.243350
2      ENSG00000269308  0.995180
3      ENSG00000187634  0.586430
4      ENSG00000268179  0.612430
...                ...       ...
14748  ENSG00000169184  0.443030
14749  ENSG00000180957  0.001488
14750  ENSG00000100154  0.004915
14751  ENSG00000183765  0.028230
14752  ENSG00000147246  0.152600

[14753 rows x 2 columns]

In [ ]:
data_prstcan.rename(columns = {'GENE':'ensemble_id', 'P':'magma_score'}, inplace = True)

In [21]:
data_prstcan.to_csv(r'/homes/mcenfeng/Documents/MAGMA/prstcan_data_fishers_calc.csv', index=False)